import NewsImg from "@/images/Lana del Rey wallpaper.jpg";
import { NewsType } from "@/types/news_slide.types";

export const news_slide_json: NewsType[] = [
  {
    id: 1,
    image: NewsImg,
    button: "Music",
    heading: "Taylor Swift's Spectacular Eras Tour: A Night to Remember",
    time: "2 hours ago",
    comment: 250,
  },
  {
    id: 2,
    image: NewsImg,
    button: "Feature",
    heading: "Beyoncé Celebrates Birthday with Fans on Renaissance World Tour",
    time: "5 hours ago",
    comment: 400,
  },
  {
    id: 3,
    image: NewsImg,
    button: "Music",
    heading: "Lana Del Rey Opens Up About Her New Album and Personal Growth",
    time: "1 day ago",
    comment: 320,
  },
  {
    id: 4,
    image: NewsImg,
    button: "Feature",
    heading: "Ed Sheeran Announces Surprise Album Drop Amidst World Tour",
    time: "3 hours ago",
    comment: 180,
  },
  {
    id: 5,
    image: NewsImg,
    button: "Music",
    heading: "Adele Talks About Balancing Motherhood and Music Career",
    time: "2 days ago",
    comment: 290,
  },
  {
    id: 6,
    image: NewsImg,
    button: "Music",
    heading: "Drake Reflects on Success and Future Plans in the Music Industry",
    time: "12 hours ago",
    comment: 350,
  },
  {
    id: 7,
    image: NewsImg,
    button: "Feature",
    heading: "Billie Eilish to Release New Song After a Year-Long Hiatus",
    time: "6 hours ago",
    comment: 150,
  },
  {
    id: 8,
    image: NewsImg,
    button: "Music",
    heading: "The Weeknd Transitions to Acting: New TV Series Confirmed",
    time: "3 days ago",
    comment: 410,
  },
  {
    id: 9,
    image: NewsImg,
    button: "Music",
    heading: "Harry Styles Seen Recording New Album in Studio Amidst Break",
    time: "7 hours ago",
    comment: 280,
  },
  {
    id: 10,
    image: NewsImg,
    button: "Music",
    heading: "Katy Perry Shares Her Journey of Self-Discovery Through Music",
    time: "4 days ago",
    comment: 220,
  },
  {
    id: 11,
    image: NewsImg,
    button: "Music",
    heading: "Rihanna Returns to the Stage: Headlining a Major Music Festival",
    time: "8 hours ago",
    comment: 330,
  },
  {
    id: 12,
    image: NewsImg,
    button: "Feature",
    heading: "Dua Lipa Speaks on Music Industry Pressures and Mental Health",
    time: "5 days ago",
    comment: 310,
  },
];
