import { route_links_types } from "@/types/route_links_types";
import { FaHome } from "react-icons/fa";
import { FaNewspaper } from "react-icons/fa6";
import Hero from "@/images/lana1.jpg";

import { favorite_links_types } from "@/types/favortie.types";
export const sidebar_route_links: route_links_types[] = [
  {
    id: 1,
    link: "Home",
    route: "/",
    icon: <FaHome />,
  },
  // {
  //   id: 2,
  //   link: "Events",
  //   route: "/events",
  //   icon: <FaCalendarDays />,
  // },

  // {
  //   id: 3,
  //   link: "Store",
  //   route: "/store",
  //   icon: <FaStore />,
  // },
  {
    id: 4,
    link: "News",
    route: "/news",
    icon: <FaNewspaper />,
  },
];

export const topbar_route_links: route_links_types[] = [
  {
    id: 1,
    link: "Profile",
    route: "/profile",
  },
  {
    id: 2,
    link: "About",
    route: "/about",
  },
  {
    id: 3,
    link: "Contacts",
    route: "/contact",
  },
];

export const favourite_route_links: favorite_links_types[] = [
  {
    id: 1,
    title: "Lana del Rey",
    subtitle: "Artist",
    image: Hero,
    route: "/artist/123",
  },
  {
    id: 2,
    title: "Lana del Rey",
    subtitle: "Artist",
    image: Hero,
    route: "/artist",
  },
  {
    id: 3,
    title: "Lana del Rey",
    subtitle: "Artist",
    image: Hero,
    route: "/artist",
  },
  {
    id: 4,
    title: "Lana del Rey",
    subtitle: "Artist",
    image: Hero,
    route: "/artist",
  },
  {
    id: 5,
    title: "Lana del Rey",
    subtitle: "Artist",
    image: Hero,
    route: "/artist",
  },
  {
    id: 6,
    title: "Lana del Rey",
    subtitle: "Artist",
    image: Hero,
    route: "/artist",
  },
  {
    id: 7,
    title: "Lana del Rey",
    subtitle: "Artist",
    image: Hero,
    route: "/artist",
  },
  {
    id: 8,
    title: "Lana del Rey",
    subtitle: "Artist",
    image: Hero,
    route: "/artist",
  },
  {
    id: 9,
    title: "Lana del Rey",
    subtitle: "Artist",
    image: Hero,
    route: "/artist",
  },
  {
    id: 10,
    title: "Lana del Rey",
    subtitle: "Artist",
    image: Hero,
    route: "/artist",
  },
  {
    id: 11,
    title: "Lana del Rey",
    subtitle: "Artist",
    image: Hero,
    route: "/artist",
  },
  {
    id: 12,
    title: "Lana del Rey",
    subtitle: "Artist",
    image: Hero,
    route: "/artist",
  },
  {
    id: 13,
    title: "Lana del Rey",
    subtitle: "Artist",
    image: Hero,
    route: "/artist",
  },
  {
    id: 14,
    title: "Lana del Rey",
    subtitle: "Artist",
    image: Hero,
    route: "/artist",
  },
  {
    id: 15,
    title: "Lana del Rey",
    subtitle: "Artist",
    image: Hero,
    route: "/artist",
  },
  {
    id: 16,
    title: "Lana del Rey",
    subtitle: "Artist",
    image: Hero,
    route: "/artist",
  },
  {
    id: 17,
    title: "Lana del Rey",
    subtitle: "Artist",
    image: Hero,
    route: "/artist",
  },
  {
    id: 18,
    title: "Lana del Rey",
    subtitle: "Artist",
    image: Hero,
    route: "/artist",
  },
  {
    id: 19,
    title: "Lana del Rey",
    subtitle: "Artist",
    image: Hero,
    route: "/artist",
  },
  {
    id: 20,
    title: "Lana del Rey",
    subtitle: "Artist",
    image: Hero,
    route: "/artist",
  },
  {
    id: 21,
    title: "Lana del Rey",
    subtitle: "Artist",
    image: Hero,
    route: "/artist",
  },
  {
    id: 22,
    title: "Lana del Rey",
    subtitle: "Artist",
    image: Hero,
    route: "/artist",
  },
  {
    id: 23,
    title: "Lana del Rey",
    subtitle: "Artist",
    image: Hero,
    route: "/artist",
  },
  {
    id: 24,
    title: "Lana del Rey",
    subtitle: "Artist",
    image: Hero,
    route: "/artist",
  },
  {
    id: 25,
    title: "Lana del Rey",
    subtitle: "Artist",
    image: Hero,
    route: "/artist",
  },
  {
    id: 26,
    title: "Lana del Rey",
    subtitle: "Artist",
    image: Hero,
    route: "/artist",
  },
  {
    id: 27,
    title: "Lana del Rey",
    subtitle: "Artist",
    image: Hero,
    route: "/artist",
  },
  {
    id: 28,
    title: "Lana del Rey",
    subtitle: "Artist",
    image: Hero,
    route: "/artist",
  },
  {
    id: 29,
    title: "Lana del Rey",
    subtitle: "Artist",
    image: Hero,
    route: "/artist",
  },
  {
    id: 30,
    title: "Lana del Rey",
    subtitle: "Artist",
    image: Hero,
    route: "/artist",
  },
  {
    id: 31,
    title: "Lana del Rey",
    subtitle: "Artist",
    image: Hero,
    route: "/artist",
  },
  {
    id: 32,
    title: "Lana del Rey",
    subtitle: "Artist",
    image: Hero,
    route: "/artist",
  },
  {
    id: 33,
    title: "Lana del Rey",
    subtitle: "Artist",
    image: Hero,
    route: "/artist",
  },
];
